# Generated by Django 6.0.1 on 2026-01-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create', 'Can create book'), ('can_edit', 'Can edit book'), ('can_delete', 'Can delete book'), ('can_view', 'Can view book')]},
        ),
    ]
